"""FakeModelProvider + stream assembly tests."""

from __future__ import annotations

import pytest

from aegis_agent.events import ModelEvent, ModelEventKind, collect_response
from aegis_agent.exceptions import ModelProviderError
from aegis_agent.models.base import Message, Role, ToolCall
from aegis_agent.models.fake import FakeModelProvider, FakeReply


def _user(text):
    return Message(role=Role.USER, content=text)


def test_scripted_text_response():
    provider = FakeModelProvider(script=[FakeReply(text="answer")])
    response = collect_response(provider.stream([_user("q")]))
    assert response.content == "answer"
    assert response.tool_calls == []
    assert response.finish_reason == "stop"


def test_scripted_tool_call_response():
    provider = FakeModelProvider(script=[FakeReply.tool("read_file", {"path": "x"}, call_id="c1")])
    response = collect_response(provider.stream([_user("read x")]))
    assert len(response.tool_calls) == 1
    assert response.tool_calls[0].name == "read_file"
    assert response.tool_calls[0].parsed_arguments() == {"path": "x"}
    assert response.finish_reason == "tool_calls"


def test_script_consumed_in_order():
    provider = FakeModelProvider(script=[FakeReply(text="first"), FakeReply(text="second")])
    assert collect_response(provider.stream([_user("1")])).content == "first"
    assert collect_response(provider.stream([_user("2")])).content == "second"


def test_chunked_text_reassembles():
    provider = FakeModelProvider(script=[FakeReply(text="abc")], chunk_text=True)
    events = list(provider.stream([_user("q")]))
    deltas = [e for e in events if e.kind is ModelEventKind.TEXT_DELTA]
    assert [e.text for e in deltas] == ["a", "b", "c"]
    assert collect_response(events).content == "abc"


def test_tool_call_id_autogenerated_when_missing():
    provider = FakeModelProvider(script=[FakeReply(tool_calls=[ToolCall(id="", name="t", arguments="{}")])])
    response = collect_response(provider.stream([_user("q")]))
    assert response.tool_calls[0].id  # got a non-empty id


def test_rule_based_read_command():
    provider = FakeModelProvider()
    response = collect_response(provider.stream([_user("read config.py")]))
    assert response.tool_calls[0].name == "read_file"
    assert response.tool_calls[0].parsed_arguments() == {"path": "config.py"}


def test_rule_based_final_summary_after_tool():
    provider = FakeModelProvider()
    tool_msg = Message(role=Role.TOOL, content='{"a": 1}', name="list_directory", tool_call_id="c1")
    response = collect_response(provider.stream([tool_msg]))
    assert response.tool_calls == []
    assert "list_directory" in response.content


def test_error_event_raises():
    events = [ModelEvent.text_delta("partial"), ModelEvent.failed("boom")]
    with pytest.raises(ModelProviderError):
        collect_response(events)


def test_toolcall_parsed_arguments_tolerates_malformed():
    assert ToolCall(id="1", name="t", arguments="not json").parsed_arguments() == {}
    assert ToolCall(id="1", name="t", arguments="").parsed_arguments() == {}
    with pytest.raises(TypeError):
        ToolCall(id="1", name="t", arguments="[1,2]").parsed_arguments()
